export const IPC_CHANNELS = {
  terminalCreate: 'terminal:create',
  terminalWrite: 'terminal:write',
  terminalSendInput: 'terminal:sendInput',
  terminalResize: 'terminal:resize',
  terminalClose: 'terminal:close',
  terminalReorder: 'terminal:reorder',
  terminalCopyBuffer: 'terminal:copyBuffer',
  terminalSaveBuffer: 'terminal:saveBuffer',
  terminalData: 'terminal:data',
  terminalExit: 'terminal:exit',
  terminalList: 'terminal:list',
  terminalStatus: 'terminal:status',
  terminalProtection: 'terminal:protection',
  workspaceCreate: 'workspace:create',
  workspaceList: 'workspace:list',
  workspaceSwitch: 'workspace:switch',
  workspaceUpdate: 'workspace:update',
  preferencesGet: 'preferences:get',
  preferencesSet: 'preferences:set',
  uiStateGet: 'uiState:get',
  uiStateSave: 'uiState:save',
  sessionList: 'session:list',
  terminalEvent: 'terminal:event',
  brokerGetContext: 'broker:getContext',
  brokerGetConflicts: 'broker:getConflicts',
  brokerConflict: 'broker:conflict',
  brokerFileChange: 'broker:fileChange',
  assistantSend: 'assistant:send',
  assistantGeneratePrompt: 'assistant:generatePrompt',
  assistantExecutePrompt: 'assistant:executePrompt',
  assistantMessage: 'assistant:message',
  assistantStreamChunk: 'assistant:stream-chunk',
  assistantSuggestion: 'assistant:suggestion',
  notificationShow: 'notification:show',
  notificationDismiss: 'notification:dismiss',
  notificationReplyRequest: 'notification:replyRequest',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
